# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sdm710-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter astro olson,$(TARGET_DEVICE)),)

endif
